spring.application.name=Restaurante

spring.data.mongodb.uri=mongodb://localhost:27017/restaurante

jwt.secret=Zm9vYmFyaXN0aGVzZWNyZXRrZXlmb3Jpc2luamd3dGF1dGhlbnRpY2F0aW9uYW5kdGVzdGluZ3B1cnBvc2VzIQ==
jwt.expiration-ms=86400000

app.admin-seed.nome=Administrador
app.admin-seed.email=admin@restaurante.com
app.admin-seed.senha=TrocarEssaSenha123

logging.level.org.springframework.security=DEBUG
logging.level.com.example.Restaurante=DEBUG